# Generated by Django 3.2.15 on 2022-08-04 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.category')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.department')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.location')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.location'),
        ),
        migrations.AddField(
            model_name='category',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.department'),
        ),
        migrations.AddField(
            model_name='category',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metadata.location'),
        ),
    ]
